### ISSUE TITLE
Steps for authentication using DB tables

### ISSUE THREAD

**Issue by smartdevops** [CognizantOneDevOps/BuildOn#3]
What is the default user name password for build on UI login with DB table authentication.?
How do I create new user to login buildon UI?

**Comment by JeyanthiBalakrishnan** [comment]
Application entities will generate the Postgres DB tables automatically. You should insert user details into the postgres DB table "buildon_users"

**Comment by smartdevops** [comment]
Jeyanthi,

I have created buildon_users and able to login the UI. After configuring the SCM details I'm facing issue when running buildon. Please find the error details in attachments
[buildonuilog.txt](https://github.com/CognizantOneDevOps/BuildOn/files/1505800/buildonuilog.txt)

Any clue on this issue ?

**Comment by JeyanthiBalakrishnan** [comment]
Please share your SCM screen shot with the  given input values.

**Comment by smartdevops** [comment]
Please find the SCM config screen shot
![image](https://user-images.githubusercontent.com/33824782/33302394-b0f288b8-d421-11e7-998c-f0fbc938ec5d.png)
![image](https://user-images.githubusercontent.com/33824782/33302415-dc9755c0-d421-11e7-81ea-eff4b5136550.png)

**Comment by JeyanthiBalakrishnan** [comment]
Please use the latest image "devopsbasservice/buildonframework:buildonJenkinsfile2.0" in your Jenkinsfile. Also, ensure you have python service configured and running. Refer: "BuildOn Framework Setup" in https://onedevops.atlassian.net/wiki/spaces/OB/pages/11108353/Installation+of+BuildOn


Python Framework source: https://github.com/CognizantOneDevOps/BuildOn/tree/master/scripts/python/src

Then, you should use the python url in webapp/src/main/resources/buildon.properties to trigger Buildon.

#Kubernetes 
python.url=
kubernetes.url=
kubernetes.namespace=
kubernetes.podport=
kubernetes.logbasepath=

Closing the issue. Since original reported issue is resolved.
